server:
    port: 8088

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://www.liyanxing.top:3306/lawyer?serverTimezone=Asia/Shanghai
        username: root
        password: root123
        type: com.alibaba.druid.pool.DruidDataSource
    thymeleaf:
        prefix: classpath:/templates/views/
        suffix: .html
        mode: LEGACYHTML5
        encoding: UTF-8
        cache: false

cbs:
     imagesPath: file:/media/root/my-disk/download/pic-dir/ # 图片存储总目录，最后有一个 "/"

mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql语句