server:
    port: 80

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1/lawyer?serverTimezone=Asia/Shanghai
        username: root
        password: root123
        type: com.alibaba.druid.pool.DruidDataSource
    thymeleaf:
        prefix: classpath:/templates/views/
        suffix: .html
        mode: LEGACYHTML5
        encoding: UTF-8
        cache: false

cbs:
     imagesPath: file:/my-dir/download/lawyer-pic-upload/ # 图片存储总目录 最后有一个 "/"